test_that("get_mermaid_project_endpoint throws an error when no project is passed, when trying to get data from a project you don't have access to, and when an unexpected endpoint is passed", {
  skip_if_offline()
  expect_error(get_mermaid_project_endpoint(), "Please supply a project to get data from")
  test_project <- search_projects("Sharla test")
  expect_error(get_mermaid_project_endpoint("ites", test_project), regexp = "endpoint must be one of")
  expect_error(get_mermaid_project_endpoint("sites", "bd115221-fde4-4e4c-bc73-1ce01b9d9fdc"), regexp = "Forbidden")
})

test_that("get_mermaid_project_endpoint returns a tibble when passed a known endpoint.", {
  skip_if_offline()
  test_project <- search_projects("Sharla test")
  set_default_project(test_project)
  expect_is(get_mermaid_project_endpoint("sites"), "tbl_df")
  output <- get_mermaid_project_endpoint("beltfishtransectmethods")
  expect_equal(names(output), mermaid_project_endpoint_columns[["beltfishtransectmethods"]])
  output <- get_mermaid_project_endpoint("beltfishes")
  expect_equal(names(output), mermaid_project_endpoint_columns[["beltfishes"]])
  output <- get_mermaid_project_endpoint("benthiclittransectmethods")
  expect_equal(names(output), mermaid_project_endpoint_columns[["benthiclittransectmethods"]])
  output <- get_mermaid_project_endpoint("benthicpittransectmethods")
  expect_equal(names(output), mermaid_project_endpoint_columns[["benthicpittransectmethods"]])
  output <- get_mermaid_project_endpoint("benthicpits")
  expect_equal(names(output), mermaid_project_endpoint_columns[["benthicpits"]])
  output <- get_mermaid_project_endpoint("collectrecords")
  expect_equal(names(output), mermaid_project_endpoint_columns[["collectrecords"]])
  output <- get_mermaid_project_endpoint("habitatcomplexities")
  expect_equal(names(output), mermaid_project_endpoint_columns[["habitatcomplexities"]])
  output <- get_mermaid_project_endpoint("obsbenthiclits")
  expect_equal(names(output), mermaid_project_endpoint_columns[["obsbenthiclits"]])
  output <- get_mermaid_project_endpoint("obsbenthicpits")
  expect_equal(names(output), mermaid_project_endpoint_columns[["obsbenthicpits"]])
  output <- get_mermaid_project_endpoint("obshabitatcomplexities")
  expect_equal(names(output), mermaid_project_endpoint_columns[["obshabitatcomplexities"]])
  output <- get_mermaid_project_endpoint("obstransectbeltfishs")
  expect_equal(names(output), mermaid_project_endpoint_columns[["obstransectbeltfishs"]])
  output <- get_mermaid_project_endpoint("managements")
  expect_equal(names(output), mermaid_project_endpoint_columns[["managements"]])
  output <- get_mermaid_project_endpoint("observers")
  expect_equal(names(output), mermaid_project_endpoint_columns[["observers"]])
  output <- get_mermaid_project_endpoint("project_profiles")
  expect_equal(names(output), mermaid_project_endpoint_columns[["project_profiles"]])
  output <- get_mermaid_project_endpoint("sampleevents")
  expect_equal(names(output), mermaid_project_endpoint_columns[["sampleevents"]])
  output <- get_mermaid_project_endpoint("sites")
  expect_equal(names(output), mermaid_project_endpoint_columns[["sites"]])
})

test_that("get_mermaid_project_endpoint returns a tibble when passed a known endpoint, even if there is no data.", {
  skip_if_offline()
  test_project <- search_projects("Sharla test")
  expect_is(get_mermaid_project_endpoint("obsbenthicpits", test_project), "tbl_df")
})
