test_that("mermaid_get_project_endpoint throws an error when no project is passed, when trying to get data from a project you don't have access to, and when an unexpected endpoint is passed", {
  skip_if_offline()
  mermaid_set_default_project("")
  expect_error(mermaid_get_project_endpoint(), "Please supply a project to get data from")
  test_project <- mermaid_search_projects("Sharla test")
  expect_error(mermaid_get_project_endpoint("bd115221-fde4-4e4c-bc73-1ce01b9d9fdc", "sites"), regexp = "Forbidden")
})

test_that("mermaid_get_project_endpoint returns a tibble when passed a known endpoint.", {
  skip_if_offline()
  test_project <- mermaid_search_projects("Sharla test")
  expect_is(mermaid_get_project_endpoint(test_project, "sites", limit = 1), "tbl_df")
  output <- mermaid_get_project_endpoint(test_project, "beltfishtransectmethods", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["beltfishtransectmethods"]])
  output <- mermaid_get_project_endpoint(test_project, "beltfishes", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["beltfishes"]])
  output <- mermaid_get_project_endpoint(test_project, "benthiclittransectmethods", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["benthiclittransectmethods"]])
  output <- mermaid_get_project_endpoint(test_project, "benthicpittransectmethods", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["benthicpittransectmethods"]])
  output <- mermaid_get_project_endpoint(test_project, "benthicpits", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["benthicpits"]])
  output <- mermaid_get_project_endpoint(test_project, "collectrecords", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["collectrecords"]])
  output <- mermaid_get_project_endpoint(test_project, "habitatcomplexities", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["habitatcomplexities"]])
  output <- mermaid_get_project_endpoint(test_project, "obsbenthiclits", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["obsbenthiclits"]])
  output <- mermaid_get_project_endpoint(test_project, "obsbenthicpits", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["obsbenthicpits"]])
  output <- mermaid_get_project_endpoint(test_project, "obshabitatcomplexities", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["obshabitatcomplexities"]])
  output <- mermaid_get_project_endpoint(test_project, "obstransectbeltfishs", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["obstransectbeltfishs"]])
  output <- mermaid_get_project_endpoint(test_project, "managements", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["managements_project"]])
  output <- mermaid_get_project_endpoint(test_project, "observers", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["observers"]])
  output <- mermaid_get_project_endpoint(test_project, "project_profiles", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["project_profiles"]])
  output <- mermaid_get_project_endpoint(test_project, "sampleevents", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["sampleevents"]])
  output <- mermaid_get_project_endpoint(test_project, "sites", limit = 1)
  expect_equal(names(output), mermaid_endpoint_columns[["sites"]])
})

test_that("mermaid_get_project_endpoint returns a tibble when passed a known endpoint, even if there is no data.", {
  skip_if_offline()
  test_project <- mermaid_search_projects("Sharla test")
  expect_is(mermaid_get_project_endpoint(test_project, "obsbenthicpits", limit = 1), "tbl_df")
})

test_that("mermaid_get_project_endpoint works for the new endpoints", {
  skip_if_offline()
  test_project <- mermaid_search_projects("Sharla test")
  expect_s3_class(mermaid_get_project_endpoint(test_project, "beltfishes/obstransectbeltfishes/", limit = 1), "tbl_df")
  expect_s3_class(mermaid_get_project_endpoint(test_project, "beltfishes/sampleunits/", limit = 1), "tbl_df")
  expect_s3_class(mermaid_get_project_endpoint(test_project, "beltfishes/sampleevents/", limit = 1), "tbl_df")
})
