test_that("get_mermaid_project_endpoint throws an error when no project is passed, when trying to get data from a project you don't have access to, and when an unexpected endpoint is passed", {
  skip_if_offline()
  expect_error(get_mermaid_project_endpoint(), "Please supply a project to get data from")
  test_project <- search_projects("Sharla test")
  expect_error(get_mermaid_project_endpoint(test_project, "ites"), regexp = "should be one of")
  expect_error(get_mermaid_project_endpoint("bd115221-fde4-4e4c-bc73-1ce01b9d9fdc", "sites"), regexp = "Unauthorized")
})

test_that("get_mermaid_project_endpoint returns a tibble when passed a known endpoint.", {
  skip_if_offline()
  test_project <- search_projects("Sharla test")
  expect_is(get_mermaid_project_endpoint(test_project, "sites"), "tbl_df")
  output <- get_mermaid_project_endpoint(test_project, "beltfishtransectmethods")
  expect_equal(names(output), mermaid_endpoint_columns[["beltfishtransectmethods"]])
  output <- get_mermaid_project_endpoint(test_project, "beltfishes")
  expect_equal(names(output), mermaid_endpoint_columns[["beltfishes"]])
  output <- get_mermaid_project_endpoint(test_project, "benthiclittransectmethods")
  expect_equal(names(output), mermaid_endpoint_columns[["benthiclittransectmethods"]])
  output <- get_mermaid_project_endpoint(test_project, "benthicpittransectmethods")
  expect_equal(names(output), mermaid_endpoint_columns[["benthicpittransectmethods"]])
  output <- get_mermaid_project_endpoint(test_project, "benthicpits")
  expect_equal(names(output), mermaid_endpoint_columns[["benthicpits"]])
  output <- get_mermaid_project_endpoint(test_project, "collectrecords")
  expect_equal(names(output), mermaid_endpoint_columns[["collectrecords"]])
  output <- get_mermaid_project_endpoint(test_project, "habitatcomplexities")
  expect_equal(names(output), mermaid_endpoint_columns[["habitatcomplexities"]])
  output <- get_mermaid_project_endpoint(test_project, "obsbenthiclits")
  expect_equal(names(output), mermaid_endpoint_columns[["obsbenthiclits"]])
  output <- get_mermaid_project_endpoint(test_project, "obsbenthicpits")
  expect_equal(names(output), mermaid_endpoint_columns[["obsbenthicpits"]])
  output <- get_mermaid_project_endpoint(test_project, "obshabitatcomplexities")
  expect_equal(names(output), mermaid_endpoint_columns[["obshabitatcomplexities"]])
  output <- get_mermaid_project_endpoint(test_project, "obstransectbeltfishs")
  expect_equal(names(output), mermaid_endpoint_columns[["obstransectbeltfishs"]])
  output <- get_mermaid_project_endpoint(test_project, "managements")
  expect_equal(names(output), mermaid_endpoint_columns[["managements_project"]])
  output <- get_mermaid_project_endpoint(test_project, "observers")
  expect_equal(names(output), mermaid_endpoint_columns[["observers"]])
  output <- get_mermaid_project_endpoint(test_project, "project_profiles")
  expect_equal(names(output), mermaid_endpoint_columns[["project_profiles"]])
  output <- get_mermaid_project_endpoint(test_project, "sampleevents")
  expect_equal(names(output), mermaid_endpoint_columns[["sampleevents"]])
  output <- get_mermaid_project_endpoint(test_project, "sites")
  expect_equal(names(output), mermaid_endpoint_columns[["sites"]])
})

test_that("get_mermaid_project_endpoint returns a tibble when passed a known endpoint, even if there is no data.", {
  skip_if_offline()
  test_project <- search_projects("Sharla test")
  expect_is(get_mermaid_project_endpoint(test_project, "obsbenthicpits"), "tbl_df")
})
